---
title: "Chapter 2: Linear Regression"
subtitle: "Distribution of the RSS Values and Hypothesis Testing for 수정하기"
author: "JuHyun, Kang"
date: "February 16, 2025"
output:
  beamer_presentation:
    latex_engine: xelatex
    theme: metropolis
  slidy_presentation: default
fonttheme: serif
fontsize: 8pt
institute: The Three Sisters of Newton \newline School of Mathematics, Statistics and Data Science \newline Sungshin Women's University
header-includes: \input{header_includes.tex}
---

# Distribution of the RSS Values

## Hat matrix
- Hat matrix defined by 


  $\hat{y} = X\hat{\beta} = X(X^TX)^{-1}{X^T}y = Hy$
$$H \mathrel{:=} X(X^TX)^{-1}{X^T}$$


- Some properties
\begin{enumerate}
\vspace{0.15cm}
\item $H^2 = H$
\vspace{0.15cm}
\item $(I -H)^2 = I - H$
\vspace{0.15cm}
\item $HX = X$
\vspace{0.15cm}
\item $H^{T} = H$
\end{enumerate}

## Residual Sum of Squares

- RSS defined
$$
\text{RSS} \mathrel{:=} ||y-\hat{y}||^2
$$

- Using hat matrix
\begin{align*}
y - \hat{y} &= y - Hy = (I-H)y = (I-H)(X\beta+\varepsilon) \\
            &= (X -HX)\beta + (I - H)\varepsilon = (I - H)\varepsilon
\end{align*}

$$
||y - \hat{y}||^2 = \{(I - H)\varepsilon\}^T (I - H)\varepsilon = \varepsilon^T(I-H)^2\varepsilon = \varepsilon^T(I-H)\varepsilon
$$

## Eigenvalues $H$ and $I-H$

- They are only zeros and ones
\vt
- Dimensions of the eigenspaces of $H$ and $I-H$ are both $p + 1$ \
\vspace{0.1cm}
\textbf{Proof} using rank$(X) = p+1$ 
\begin{align*}
\text{rank}(H) &\le \text{min}\{\text{rank}(X(X^TX)^{-1}), \text{rank}(X)\} \le \text{rank}(X) = p + 1 \\
\text{rank}(H) &\ge \text{rank}(HX) = \text{rank}(X) = p + 1
\end{align*}


## Eigenvalues of $H$ and Null space of ($I-H$)
- Proof by contrapositive
\begin{align*}
Hx = x \Rightarrow (I - H)x = 0 \\
(I - H)x = 0 \Rightarrow Hx = x
\end{align*}
- Dimensions of the eigenspaces of $H$ is $p + 1$ \
\vt
\textbf{Proof} using rank($X) = p+1$ 
\begin{align*}
\text{rank}(H) &\le \text{min}\{\text{rank}(X(X^TX)^{-1}), \text{rank}(X)\} \le \text{rank}(X) = p + 1 \\
\text{rank}(H) &\ge \text{rank}(HX) = \text{rank}(X) = p + 1
\end{align*}

- Dimensions of the null space of $I-H$ is $N - (p+1)$

$$
P (I - H) P^T = \operatorname{diag}(\underbrace{1, \dots, 1}_{N-p-1}, \underbrace{0, \dots, 0}_{p+1})
$$

## RSS
-  We define $v = P\varepsilon \in \mathbb{R}^N$, then from $\varepsilon = P^Tv$
\begin{align*}
\text{RSS} 
&= \varepsilon^T(I - H)\varepsilon = (P^Tv)^T(I-H)P^Tv = v^TP(I-H)P^Tv \\
&= [v_1, \cdots, v_{N-p-1}, v_{N-p}, \cdots, v_n] 
\begin{bmatrix}
1      & 0      &\cdots  &  \cdots & \cdots & 0 \\
0      & \ddots & 0      &  \cdots & \cdots & \vdots \\
\vdots & 0      & 1      &  \cdots & \cdots & 0 \\
0      & 0      & 0      &  \cdots & \cdots & \cdots \\
\vdots & \vdots & \vdots &  \vdots & \ddots & \vdots \\
0      & \cdots & 0      &  \cdots & \cdots & 0
\end{bmatrix}
\begin{bmatrix}
v_1 \\
\vdots \\
v_{N-p-1} \\
v_{N-p} \\
\vdots \\
v_N
\end{bmatrix} 
&= \sum^{N-p-1}_{i = 1}v_i^2
\end{align*}

## Distribution of RSS
- Let $w \in \mathbb{R}^{N-p-1}$
\vt
- Average 

  $E[v] = E[P\varepsilon] = 0$

  $E[w] = 0$
\vt

- Covariance 

  $E[vv^t] = E[P\varepsilon(P\varepsilon)^T] = PE[\varepsilon\varepsilon^t]P=P\sigma^2IP^T = \sigma^2I$
  
  $E[ww^T] = \sigma^2I$
\vt

- We have RSS
$$
\frac{RSS}{\sigma^2} \sim \chi^2_{N-p-1}
$$

# Hypothesis Testing for $\hat{\beta}_j \ne 0$

## Test statistic $T$
- A t distribution with $N - P -1$ degrees of freedom
\vt
- We decide that hypothesis $\beta_j = 0$ should be rejected.
\vt
- $U \sim N(0,1),\ V \sim \chi^2_m$, 

$$
T \triangleq U / \sqrt{V/m}
$$

```{r fig.height=5, fig.width=10, message=FALSE}
curve(dnorm(x), -10, 10, ann = FALSE, ylim = c(0, 0.5), lwd = 5)
for(i in 1:10)curve(dt(x, df= i), -10, 10, col = i, add = TRUE, ann = FALSE)
legend("topright", legend = 1:10, lty = 1, col = 1:10)
```

## Significance level
- $\alpha = 0.01,\ 0.05$
\vt
- Reject the null hypothesis 


## Q & A

\begin{center}
  {\bf {\Huge Q \& A}}
\end{center}

## 

\begin{center}
  {\bf {\Huge Thank you :)}}
\end{center}

